-- MySQL Script generated by MySQL Workbench
-- Sun 29 Oct 2017 08:15:20 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema CursoCalidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CursoCalidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CursoCalidad` DEFAULT CHARACTER SET latin1 ;
USE `CursoCalidad` ;

-- -----------------------------------------------------
-- Table `CursoCalidad`.`CursoCalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`CursoCalidad` (
  `id` INT(6) NOT NULL AUTO_INCREMENT,
  `cod_autor` INT(30) NULL DEFAULT NULL,
  `cod_libro` INT(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`autor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`autor-tesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`autor-tesis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`libro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `edicion` VARCHAR(100) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `idioma` VARCHAR(40) NOT NULL,
  `portadaPhoto` VARCHAR(13) NOT NULL,
  `anio` INT(4) NOT NULL,
  `num_ingreso` INT(6) NOT NULL,
  `num_hoja` INT(4) NOT NULL,
  `fecha_ingreso` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`libros-por-autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`libros-por-autor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `libroId` INT(11) NOT NULL,
  `autorsId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `autorsId` (`autorsId` ASC),
  INDEX `libroId` (`libroId` ASC),
  CONSTRAINT `FK_Libro`
    FOREIGN KEY (`libroId`)
    REFERENCES `CursoCalidad`.`libro` (`id`),
  CONSTRAINT `FK_autor`
    FOREIGN KEY (`autorsId`)
    REFERENCES `CursoCalidad`.`autor` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`libros-por-categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`libros-por-categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `libroId` INT(11) NOT NULL,
  `categoriaId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_LibroC` (`libroId` ASC),
  INDEX `FK_categoriaL` (`categoriaId` ASC),
  CONSTRAINT `FK_LibroC`
    FOREIGN KEY (`libroId`)
    REFERENCES `CursoCalidad`.`libro` (`id`),
  CONSTRAINT `FK_categoriaL`
    FOREIGN KEY (`categoriaId`)
    REFERENCES `CursoCalidad`.`categoria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`tipo-usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`tipo-usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_usuario` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fechaNac` DATE NOT NULL,
  `escuela` VARCHAR(100) NOT NULL,
  `tipoUsuarioId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_TipoUsuario` (`tipoUsuarioId` ASC),
  CONSTRAINT `FK_TipoUsuario`
    FOREIGN KEY (`tipoUsuarioId`)
    REFERENCES `CursoCalidad`.`tipo-usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`login` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_usuario` INT(11) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `usuarioId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_LoginUsuario` (`usuarioId` ASC),
  CONSTRAINT `FK_LoginUsuario`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `CursoCalidad`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`tipo-valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`tipo-valoracion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`opinion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`opinion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codUsuarioId` INT(11) NOT NULL,
  `libroId` INT(11) NOT NULL,
  `tipoValoracionId` INT(11) NOT NULL,
  `comentario` VARCHAR(1000) NOT NULL,
  `fecha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_OpinionesLibro` (`libroId` ASC),
  INDEX `FK_OpinionesTipo_valoracion` (`tipoValoracionId` ASC),
  INDEX `FK_OpinionesUsuario` (`codUsuarioId` ASC),
  CONSTRAINT `FK_OpinionesLibro`
    FOREIGN KEY (`libroId`)
    REFERENCES `CursoCalidad`.`libro` (`id`),
  CONSTRAINT `FK_OpinionesTipo_valoracion`
    FOREIGN KEY (`tipoValoracionId`)
    REFERENCES `CursoCalidad`.`tipo-valoracion` (`id`),
  CONSTRAINT `FK_OpinionesUsuario`
    FOREIGN KEY (`codUsuarioId`)
    REFERENCES `CursoCalidad`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`tesis-tesina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`tesis-tesina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `resumen` VARCHAR(1000) NOT NULL,
  `escuela` VARCHAR(100) NOT NULL,
  `anio` INT(4) NOT NULL,
  `num_ingreso` INT(6) NOT NULL,
  `num_hojas` INT(11) NOT NULL,
  `fecha_ingreso` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`prestamo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuarioId` INT(11) NOT NULL,
  `libroId` INT(11) NOT NULL,
  `tesis-tesinaId` INT(11) NOT NULL,
  `fecha_emision` VARCHAR(20) NOT NULL,
  `fecha_entrega` VARCHAR(20) NOT NULL,
  `fecha_maxina` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PrestamoLibro` (`libroId` ASC),
  INDEX `FK_PrestamoTesis_tesina` (`tesis-tesinaId` ASC),
  INDEX `FK_PrestamoUsuario` (`usuarioId` ASC),
  CONSTRAINT `FK_PrestamoLibro`
    FOREIGN KEY (`libroId`)
    REFERENCES `CursoCalidad`.`libro` (`id`),
  CONSTRAINT `FK_PrestamoTesis_tesina`
    FOREIGN KEY (`tesis-tesinaId`)
    REFERENCES `CursoCalidad`.`tesis-tesina` (`id`),
  CONSTRAINT `FK_PrestamoUsuario`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `CursoCalidad`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`tesis-tesina-por-autor-tesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`tesis-tesina-por-autor-tesis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `autor-tesisId` INT(11) NOT NULL,
  `tesis-tesinaId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_autor_tesis` (`autor-tesisId` ASC),
  INDEX `FK_tesis_tesinaBy` (`tesis-tesinaId` ASC),
  CONSTRAINT `FK_autor_tesis`
    FOREIGN KEY (`autor-tesisId`)
    REFERENCES `CursoCalidad`.`autor-tesis` (`id`),
  CONSTRAINT `FK_tesis_tesinaBy`
    FOREIGN KEY (`tesis-tesinaId`)
    REFERENCES `CursoCalidad`.`tesis-tesina` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `CursoCalidad`.`tesis-tesina-por-categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CursoCalidad`.`tesis-tesina-por-categoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoriaId` INT(11) NOT NULL,
  `tesis-tesinaId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_categoria` (`categoriaId` ASC),
  INDEX `FK_tesis_tesina` (`tesis-tesinaId` ASC),
  CONSTRAINT `FK_categoria`
    FOREIGN KEY (`categoriaId`)
    REFERENCES `CursoCalidad`.`categoria` (`id`),
  CONSTRAINT `FK_tesis_tesina`
    FOREIGN KEY (`tesis-tesinaId`)
    REFERENCES `CursoCalidad`.`tesis-tesina` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
